use illegacy_lib::parsers::c_parser::CParser;
use illegacy_lib::generators::python_gen::PythonGenerator;
use illegacy_lib::generators::Generator;

// Вспомогательная функция для нормализации кода
fn normalize_code(code: &str) -> String {
    code.lines()
        .map(|line| line.trim_end())
        .filter(|line| !line.is_empty())
        .collect::<Vec<_>>()
        .join("\n")
        .trim()
        .to_string()
}

// Вспомогательная функция для тестирования трансляции
async fn test_translation(c_code: &str, expected_python: &str) {
    let ast = CParser::parse_async(c_code).await
        .expect("Парсинг C кода не удался");
    
    let python_code = PythonGenerator::generate(&ast)
        .expect("Генерация Python кода не удалась");
    
    let normalized_expected = normalize_code(expected_python);
    let normalized_actual = normalize_code(&python_code);
    
    assert_eq!(
        normalized_actual, 
        normalized_expected,
        "\nТест не пройден!\n\nОЖИДАЛОСЬ:\n{}\n\nПОЛУЧЕНО:\n{}\n",
        normalized_expected, normalized_actual
    );
}

// Шапка, которая всегда добавляется к генерируемому коду
const GENERATED_HEADER: &str = r#"# Generated by C to Python transpiler
# This is an approximate conversion
import sys
import os
import enum
from enum import auto
# Класс для имитации ссылок и указателей C
class Reference:
    def __init__(self, value):
        # Сохраняем ссылку на объект
        self._ref = value
    @property
    def value(self):
        # Возвращаем ссылку на следующий объект в цепочке
        if isinstance(self._ref, Reference):
            return self._ref
        else:
            return self._ref
    @value.setter
    def value(self, new_value):
        if isinstance(self._ref, Reference):
            self._ref.value = new_value
        else:
            self._ref = new_value
    def get(self):
        # Получаем конечное значение по цепочке ссылок
        if isinstance(self._ref, Reference):
            return self._ref.get()
        elif hasattr(self._ref, 'value') and not isinstance(self._ref, Reference):
            return self._ref.value
        else:
            return self._ref
    # Для обратной совместимости
    def get_final_value(self):
        return self.get()
    def __getattr__(self, name):
        if name == '_ref':
            return super().__getattr__(name)
        final_obj = self.get()
        return getattr(final_obj, name)
    def __setattr__(self, name, value):
        if name == '_ref':
            super().__setattr__(name, value)
        elif name == 'value':
            if isinstance(self._ref, Reference):
                self._ref.value = value
            else:
                self._ref = value
        else:
            final_obj = self.get()
            setattr(final_obj, name, value)
    def __repr__(self):
        return f"Reference({self.get()})"
    def __add__(self, other):
        return Reference(self.get() + other)
    def __sub__(self, other):
        return Reference(self.get() - other)
    def __getitem__(self, index):
        val = self.get()
        return val[index] if hasattr(val, '__getitem__') else val + index
    def __setitem__(self, index, value):
        val = self.get()
        if hasattr(val, '__setitem__'):
            val[index] = value
        else:
            self.value = value - index
"#;

// ТЕСТЫ ДЛЯ СТРУКТУР

#[tokio::test]
async fn test_struct_simple() {
    let c_code = r#"
struct Point {
    int x;
    int y;
};
"#;

    let expected = format!(r#"{}
class Point:
    def __init__(self, x = None, y = None):
        self.x = x
        self.y = y
"#, GENERATED_HEADER);

    test_translation(c_code, &expected).await;
}

#[tokio::test]
async fn test_struct_nested() {
    let c_code = r#"
struct Point {
    int x;
    int y;
};

struct Rectangle {
    struct Point top_left;
    struct Point bottom_right;
    int area;
};
"#;

    let expected = format!(r#"{}
class Point:
    def __init__(self, x = None, y = None):
        self.x = x
        self.y = y

class Rectangle:
    def __init__(self, top_left = None, bottom_right = None, area = None):
        self.top_left = top_left
        self.bottom_right = bottom_right
        self.area = area
"#, GENERATED_HEADER);

    test_translation(c_code, &expected).await;
}

// ТЕСТЫ ДЛЯ ОБЪЕДИНЕНИЙ

#[tokio::test]
async fn test_union_simple() {
    let c_code = r#"
union IntOrChar {
    int integer;
    char character;
};
"#;

    let expected = format!(r#"{}
class IntOrChar:
    def __init__(self):
        self.integer = None
        self.character = None
"#, GENERATED_HEADER);

    test_translation(c_code, &expected).await;
}

#[tokio::test]
async fn test_union_with_struct() {
    let c_code = r#"
struct Point {
    int x;
    int y;
};

union Coordinate {
    struct {
        int x;
        int y;
    } point;
    float single_value;
};
"#;

    let expected = format!(r#"{}
class Coordinate_point:
    def __init__(self):
        pass

class Coordinate:
    def __init__(self):
        self.single_value = None
        self.point = Coordinate_point()

class Point:
    def __init__(self, x = None, y = None):
        self.x = x
        self.y = y
"#, GENERATED_HEADER);

    test_translation(c_code, &expected).await;
}

//  ТЕСТЫ ДЛЯ ОБЪЯВЛЕНИЙ ПЕРЕМЕННЫХ 

#[tokio::test]
async fn test_variable_declarations_basic() {
    let c_code = r#"
int main() {
    int a;
    int b = 20;
    int c = -1;
}
"#;

    let expected = format!(r#"{}
def main():
    a = None
    b = 20
    c = -1

if __name__ == "__main__":
    main()
"#, GENERATED_HEADER);

    test_translation(c_code, &expected).await;
}

#[tokio::test]
async fn test_variable_declarations_arrays() {
    let c_code = r#"
int main() {
    int arr[5] = {1, 2, 3, 4, 5};
    int table[2][3] = {{1, 2, 3}, {4, 5, 6}};
    int sec[] = {1,2,3};
    int th[3] = {3,2,1};
    char str[255] = "name";
}
"#;

    let expected = format!(r#"{}
def main():
    arr = [1, 2, 3, 4, 5]
    table = [[1, 2, 3], [4, 5, 6]]
    sec = [1, 2, 3]
    th = [3, 2, 1]
    str = "name"

if __name__ == "__main__":
    main()
"#, GENERATED_HEADER);

    test_translation(c_code, &expected).await;
}

#[tokio::test]
async fn test_variable_declarations_structs() {
    let c_code = r#"
struct Point {
    int x;
    int y;
};

int main() {
    struct Point p1;
    p1.x = 10;
    p1.y = 20;
    
    struct Point p2 = {30, 40};
}
"#;

    let expected = format!(r#"{}
class Point:
    def __init__(self, x = None, y = None):
        self.x = x
        self.y = y

def main():
    p1 = Point(None, None)
    p1.x = 10
    p1.y = 20
    p2 = Point(30, 40)

if __name__ == "__main__":
    main()
"#, GENERATED_HEADER);

    test_translation(c_code, &expected).await;
}

//  ТЕСТЫ ДЛЯ ОПЕРАЦИЙ 

#[tokio::test]
async fn test_operations_arithmetic() {
    let c_code = r#"
int main() {
    int a = 18;
    a = a - 9;
    a = -1;
}
"#;

    let expected = format!(r#"{}
def main():
    a = 18
    a = a - 9
    a = -1

if __name__ == "__main__":
    main()
"#, GENERATED_HEADER);

    test_translation(c_code, &expected).await;
}

#[tokio::test]
async fn test_operations_increment_decrement() {
    let c_code = r#"
int main() {
    int a = 18;
    a++;
    ++a;
    a--;
    --a;
}
"#;

    let expected = format!(r#"{}
def main():
    a = 18
    a += 1
    a += 1
    a -= 1
    a -= 1

if __name__ == "__main__":
    main()
"#, GENERATED_HEADER);

    test_translation(c_code, &expected).await;
}

//  ТЕСТЫ ДЛЯ УПРАВЛЯЮЩИХ КОНСТРУКЦИЙ 

#[tokio::test]
async fn test_if_else_simple() {
    let c_code = r#"
int main() {
    int a = 25;
    int result;
    
    if (a > 20) {
        result = 1;
    } else {
        result = -1;
    }
}
"#;

    let expected = format!(r#"{}
def main():
    a = 25
    result = None
    if a > 20:
        result = 1
    else:
        result = -1

if __name__ == "__main__":
    main()
"#, GENERATED_HEADER);

    test_translation(c_code, &expected).await;
}

#[tokio::test]
async fn test_if_else_chain() {
    let c_code = r#"
int main() {
    int a = 25;
    int result;
    
    if (a > 40) {
        result = 3;
    } else if (a > 30) {
        result = 2;
    } else if (a > 20) {
        result = 1;
    } else {
        result = -1;
    }
}
"#;

    let expected = format!(r#"{}
def main():
    a = 25
    result = None
    if a > 40:
        result = 3
    elif a > 30:
        result = 2
    elif a > 20:
        result = 1
    else:
        result = -1

if __name__ == "__main__":
    main()
"#, GENERATED_HEADER);

    test_translation(c_code, &expected).await;
}

#[tokio::test]
async fn test_switch_statement() {
    let c_code = r#"
int main() {
    int result = 2;
    
    switch (result) {
        case 1:
            result += 1;
            break;
        case 2:
            result += 2;
            break;
        case 3:
            result += 3;
            break;
        default:
            result = 0;
            break;
    }
}
"#;

    let expected = format!(r#"{}
def main():
    result = 2
    match result:
        case 1:
            result += 1
        case 2:
            result += 2
        case 3:
            result += 3
        case _:
            result = 0

if __name__ == "__main__":
    main()
"#, GENERATED_HEADER);

    test_translation(c_code, &expected).await;
}

#[tokio::test]
async fn test_ternary_operator() {
    let c_code = r#"
int main() {
    int result = 0;
    float post = (result == 0) ? 0.5 : 1.3;
}
"#;

    let expected = format!(r#"{}
def main():
    result = 0
    post = 0.5 if result == 0 else 1.3

if __name__ == "__main__":
    main()
"#, GENERATED_HEADER);

    test_translation(c_code, &expected).await;
}

//  ТЕСТЫ ДЛЯ ЦИКЛОВ 

#[tokio::test]
async fn test_while_loop() {
    let c_code = r#"
int main() {
    int val = 0;
    while (val < 10) {
        val++;
    }
}
"#;

    let expected = format!(r#"{}
def main():
    val = 0
    while val < 10:
        val += 1

if __name__ == "__main__":
    main()
"#, GENERATED_HEADER);

    test_translation(c_code, &expected).await;
}

#[tokio::test]
async fn test_do_while_loop() {
    let c_code = r#"
int main() {
    int val = 0;
    do {
        val--;
    } while(val < 10);
}
"#;

    let expected = format!(r#"{}
def main():
    val = 0
    while True:
        val -= 1
        if not (val < 10):
            break

if __name__ == "__main__":
    main()
"#, GENERATED_HEADER);

    test_translation(c_code, &expected).await;
}

#[tokio::test]
async fn test_for_loop_simple() {
    let c_code = r#"
int main() {
    for (int j = 0; j < 5; j++) {
        j++;
    }
}
"#;

    let expected = format!(r#"{}
def main():
    # Преобразование for цикла из C в while
    j = 0
    while j < 5:
        j += 1
        j += 1

if __name__ == "__main__":
    main()
"#, GENERATED_HEADER);

    test_translation(c_code, &expected).await;
}

#[tokio::test]
async fn test_nested_for_loops() {
    let c_code = r#"
int main() {
    for (int i = 0; i < 5; i++) {
        for (int j = 0; j < 5; j++) {
            i *= j;
        }
    }
}
"#;

    let expected = format!(r#"{}
def main():
    # Преобразование for цикла из C в while
    i = 0
    while i < 5:
        # Преобразование for цикла из C в while
        j = 0
        while j < 5:
            i *= j
            j += 1
        i += 1

if __name__ == "__main__":
    main()
"#, GENERATED_HEADER);

    test_translation(c_code, &expected).await;
}

//  ТЕСТЫ ДЛЯ ФУНКЦИЙ 

#[tokio::test]
async fn test_function_simple() {
    let c_code = r#"
int foo(int x, int y) {
    return x + y;
}
"#;

    let expected = format!(r#"{}
def foo(x, y):
    # Параметры-указатели (ожидают объекты Reference):
    # x: Reference
    # y: Reference
    return x + y
"#, GENERATED_HEADER);

    test_translation(c_code, &expected).await;
}

#[tokio::test]
async fn test_function_with_main() {
    let c_code = r#"
int foo(int x, int y) {
    return x + y;
}

int main() {
    int a = 10;
    int b = 20;
    int c = foo(a, b);
}
"#;

    let expected = format!(r#"{}
def foo(x, y):
    # Параметры-указатели (ожидают объекты Reference):
    # x: Reference
    # y: Reference
    return x + y

def main():
    a = 10
    b = 20
    c = foo(a, b)

if __name__ == "__main__":
    main()
"#, GENERATED_HEADER);

    test_translation(c_code, &expected).await;
}
//  КОМПЛЕКСНЫЙ ТЕСТ 
#[tokio::test]
async fn test_c_to_python_comprehensive() {
    let c_code = r#"
enum Color {
    RED,
    GREEN,
    BLUE
};

struct Point {
    int x;
    int y;
};

struct Rectangle {
    struct Point top_left;
    struct Point bottom_right;
    int area;
};

union IntOrChar {
    int integer;
    char character;
};

union Coordinate {
    struct {
        int x;
        int y;
    } point;
    float single_value;
};

int main(){

    int x = 10;
    int *ptr = &x;
    *ptr = 20;

    union IntOrChar data1;
    data1.integer = 42;

    union IntOrChar data2;
    data2.character = 'A';

    union Coordinate coord1;
    coord1.point.x = 10;
    coord1.point.y = 20;

    union Coordinate coord2;
    coord2.single_value = 15.5f;

    struct Point p1;
    p1.x = 10;
    p1.y = 20;

    struct Point p2 = {30, 40};

    struct Rectangle rect;
    rect.top_left = p1;
    rect.bottom_right = p2;
    rect.area = (rect.bottom_right.x - rect.top_left.x) * (rect.bottom_right.y - rect.top_left.y);

    int arr[5] = {1, 2, 3, 4, 5};
    int table[2][3] = {{1, 2, 3}, {4, 5, 6}};
    int sec[] = {1,2,3};
    int th[3]={3,2,1};
    char str[255] = "name";
    int a;
    a=18;
    a++;
    ++a;
    a--;
    --a;
    a = -1;

    int b = 20;
    b = a -9;
    int c = foo(a, b);
    int result;
    if (a > 20){
        result = 1;
    } else if ( a > 30){
        result = 2;
    } else if (a > 40){
        result = 3;
    } else {
        result = -1;
    }

    switch (result){
        case 1:
            result +=1;
            break;
        case 2:
            result += 2;
            break;
        case 3:
            result += 3;
            break;
        default:
            result = 0;
            break;
    }
    float post = (result == 0) ? 0.5 : 1.3;

    int val = 0;
    while (val < 10){
        val ++;
    }

    do{
        val--;
    }while(val<10);

    for (int j = 0; j < 5; j++){
        for (int i = 0; i < 5; i++){
            i *= j;
        }
    }

    enum Color my_color = RED;
    enum Color another_color = GREEN;
    enum Color third_color = BLUE;

    if (my_color == RED) {
        my_color = GREEN;
    }

    switch (my_color) {
        case RED:
            result = 1;
            break;
        case GREEN:
            result = 2;
            break;
        case BLUE:
            result = 3;
            break;
    }

    return 0;
}

int foo(int x, int y){
    return x+y;
}
"#;

    let expected_python = format!(r#"{}
class Color(enum.Enum):
    RED = 0
    GREEN = 1
    BLUE = 2

class IntOrChar:
    def __init__(self):
        self.integer = None
        self.character = None

class Coordinate_point:
    def __init__(self):
        pass

class Coordinate:
    def __init__(self):
        self.single_value = None
        self.point = Coordinate_point()

class Point:
    def __init__(self, x = None, y = None):
        self.x = x
        self.y = y

class Rectangle:
    def __init__(self, top_left = None, bottom_right = None, area = None):
        self.top_left = top_left
        self.bottom_right = bottom_right
        self.area = area

def main():
    x = 10
    ptr = Reference(x)
    ptr.value = 20
    data1 = IntOrChar()
    data1.integer = 42
    data2 = IntOrChar()
    data2.character = 65
    coord1 = Coordinate()
    coord1.point.x = 10
    coord1.point.y = 20
    coord2 = Coordinate()
    coord2.single_value = 15.5
    p1 = Point(None, None)
    p1.x = 10
    p1.y = 20
    p2 = Point(30, 40)
    rect = Rectangle(None, None, None)
    rect.top_left = p1
    rect.bottom_right = p2
    rect.area = (rect.bottom_right.x - rect.top_left.x) * (rect.bottom_right.y - rect.top_left.y)
    arr = [1, 2, 3, 4, 5]
    table = [[1, 2, 3], [4, 5, 6]]
    sec = [1, 2, 3]
    th = [3, 2, 1]
    str = "name"
    a = None
    a = 18
    a += 1
    a += 1
    a -= 1
    a -= 1
    a = -1
    b = 20
    b = a - 9
    c = foo(a, b)
    result = None
    if a > 20:
        result = 1
    elif a > 30:
        result = 2
    elif a > 40:
        result = 3
    else:
        result = -1
    match result:
        case 1:
            result += 1
        case 2:
            result += 2
        case 3:
            result += 3
        case _:
            result = 0
    post = 0.5 if result == 0 else 1.3
    val = 0
    while val < 10:
        val += 1
    while True:
        val -= 1
        if not (val < 10):
            break
    # Преобразование for цикла из C в while
    j = 0
    while j < 5:
        # Преобразование for цикла из C в while
        i = 0
        while i < 5:
            i *= j
            i += 1
        j += 1
    my_color = Color.RED.value
    another_color = Color.GREEN.value
    third_color = Color.BLUE.value
    if my_color == Color.RED.value:
        my_color = Color.GREEN.value
    match my_color:
        case Color.RED.value:
            result = 1
        case Color.GREEN.value:
            result = 2
        case Color.BLUE.value:
            result = 3
    return 0

def foo(x, y):
    # Параметры-указатели (ожидают объекты Reference):
    # x: Reference
    # y: Reference
    return x + y

if __name__ == "__main__":
    main()
"#, GENERATED_HEADER);

    test_translation(c_code, &expected_python).await;
}
