use illegacy_lib::parsers::c_parser::CParser;
use illegacy_lib::generators::python_gen::PythonGenerator;
use illegacy_lib::generators::Generator;  // <-- ВАЖНО: импорт трейта!

// Вспомогательная функция для нормализации кода
fn normalize_code(code: &str) -> String {
    code.lines()
        .map(|line| line.trim_end())
        .filter(|line| !line.is_empty())
        .collect::<Vec<_>>()
        .join("\n")
        .trim()
        .to_string()
}

#[tokio::test]
async fn test_complete_example() {
    // Входной C код - используем &str, а не String
    let c_code = r#"
int main(){
    int arr = {1, 2, 3, 4, 5};
    int sec[] = {1,2,3};
    int th[3]={3,2,1};
    char str[255] = "name";
    int a;
    a=18;
    a++;
    ++a;
    a--;
    --a;
    a = -1;

    int b = 20;
    b = a -9;
    int c = foo(a, b);
    int result;
    if (a > 20){
        result = 1;
    } else if ( a > 30){
        result = 2;
    } else if (a > 40){
        result = 3;
    } else {
        result = -1;
    }

    switch (result){
        case 1:
            result +=1;
            break;
        case 2:
            result += 2;
            break;
        case 3:
            result += 3;
            break;
        default:
            result = 0;
            break;
    }
    float post = (result == 0) ? 0.5 : 1.3;

    int val = 0;
    while (val < 10){
        val ++;
    }

    do{
        val--;
    }while(val<10);
    
    for (int j = 0; j < 5; j++){
    	for (int i = 0; i < 5; i++){
    		i *= j;
    	}
    }
    return 0;
}

int foo(int x, int y){
    return x+y;
}

"#;

    // Ожидаемый Python код
    let expected_python = r#"
# Generated by C to Python transpiler
# This is an approximate conversion

import sys
import os

def main():
    arr = [1, 2, 3, 4, 5]
    sec = [1, 2, 3]
    th = [3, 2, 1]
    str = "name"
    a = None
    a = 18
    a += 1
    a += 1
    a -= 1
    a -= 1
    a = -1
    b = 20
    b = a - 9
    c = foo(a, b)
    result = None
    if a > 20:
        result = 1
    elif a > 30:
        result = 2
    elif a > 40:
        result = 3
    else:
        result = -1
    match result:
        case 1:
            result += 1
        case 2:
            result += 2
        case 3:
            result += 3
        case _:
            result = 0
    post = 0.5 if result == 0 else 1.3
    val = 0
    while val < 10:
        val += 1
    while True:
        val -= 1
        if not (val < 10):
            break
    # Преобразование for цикла из C в while
    j = 0
    while j < 5:
        # Преобразование for цикла из C в while
        i = 0
        while i < 5:
            i *= j
            i += 1
        j += 1
    return 0

def foo(x, y):
    return x + y


"#;

    println!("Запуск комплексного теста...");
    
    // Парсинг C кода
    println!("Парсинг C кода...");
    let ast = match CParser::parse_async(c_code).await {
        Ok(ast) => {
            println!("Парсинг успешен");
            ast
        }
        Err(e) => {
            panic!("Ошибка парсинга: {}", e);
        }
    };
    
    // Генерация Python кода
    println!("Генерация Python кода...");
    let python_code = match PythonGenerator::generate(&ast) {
        Ok(code) => {
            println!("Генерация успешна");
            code
        }
        Err(e) => {
            panic!("Ошибка генерации: {}", e);
        }
    };
    
    // Вывод полученного кода для отладки
    println!("\n=== СГЕНЕРИРОВАННЫЙ КОД ===\n{}", python_code);
    
    // Нормализация для сравнения
    let normalized_expected = normalize_code(expected_python);
    let normalized_actual = normalize_code(&python_code);
    
    assert_eq!(
        normalized_actual, 
        normalized_expected,
        "\nКомплексный тест не пройден!\n\nОЖИДАЛОСЬ:\n{}\n\nПОЛУЧЕНО:\n{}\n",
        normalized_expected, normalized_actual
    );
    
    println!("Комплексный тест успешно пройден!");
}